export const FALLBACK_VERSES = [
    // --- FORTALEZA, FE Y AMPARO ---
    { book: 'Josué', chapter: '1', verse: '9', text: 'Mira que te mando que te esfuerces y seas valiente; no temas ni desmayes, porque Jehová tu Dios estará contigo en dondequiera que vayas.' },
    { book: 'Proverbios', chapter: '3', verse: '5', text: 'Fíate de Jehová de todo tu corazón, y no te apoyes en tu propia prudencia.' },
    { book: 'Isaías', chapter: '41', verse: '10', text: 'No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo; siempre te ayudaré, siempre te sustentaré con la diestra de mi justicia.' },
    { book: 'Jeremías', chapter: '29', verse: '11', text: 'Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz, y no de mal, para daros el fin que esperáis.' },
    { book: 'Mateo', chapter: '11', verse: '28', text: 'Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.' },
    { book: 'Juan', chapter: '14', verse: '6', text: 'Jesús le dijo: Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.' },
    { book: 'Romanos', chapter: '8', verse: '28', text: 'Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien, esto es, a los que conforme a su propósito son llamados.' },
    { book: 'Filipenses', chapter: '4', verse: '13', text: 'Todo lo puedo en Cristo que me fortalece.' },
    { book: 'Hebreos', chapter: '11', verse: '1', text: 'Es, pues, la fe la certeza de lo que se espera, la convicción de lo que no se ve.' },
    { book: 'Salmos', chapter: '23', verse: '1', text: 'Jehová es mi pastor; nada me faltará.' },
    { book: 'Salmos', chapter: '27', verse: '1', text: 'Jehová es mi luz y mi salvación; ¿de quién temeré? Jehová es la fortaleza de mi vida; ¿de quién he de atemorizarme?' },
    { book: 'Salmos', chapter: '46', verse: '1', text: 'Dios es nuestro amparo y fortaleza, Nuestro pronto auxilio en las tribulaciones.' },
    { book: 'Salmos', chapter: '119', verse: '105', text: 'Lámpara es a mis pies tu palabra, Y lumbrera a mi camino.' },
    { book: '1 Corintios', chapter: '16', verse: '13', text: 'Velad, estad firmes en la fe; portaos varonilmente, y esforzaos.' },
    { book: 'Isaías', chapter: '40', verse: '31', text: 'Pero los que esperan a Jehová tendrán nuevas fuerzas; levantarán alas como las águilas; correrán, y no se cansarán; caminarán, y no se fatigarán.' },
    { book: 'Nahúm', chapter: '1', verse: '7', text: 'Jehová es bueno, fortaleza en el día de la angustia; y conoce a los que en él confían.' },
    { book: 'Salmos', chapter: '34', verse: '4', text: 'Busqué a Jehová, y él me oyó, Y me libró de todos mis temores.' },
    { book: 'Proverbios', chapter: '18', verse: '10', text: 'Torre fuerte es el nombre de Jehová; A él correrá el justo, y será levantado.' },
    { book: 'Deuteronomio', chapter: '31', verse: '6', text: 'Esforzaos y cobrad ánimo; no temáis, ni tengáis miedo de ellos, porque Jehová tu Dios es el que va contigo; no te dejará, ni te desamparará.' },
    { book: 'Salmos', chapter: '18', verse: '2', text: 'Jehová, roca mía y castillo mío, y mi libertador; Dios mío, fortaleza mía, en él confiaré; Mi escudo, y la fuerza de mi salvación, mi alto refugio.' },
    { book: '2 Corintios', chapter: '12', verse: '9', text: 'Y me ha dicho: Bástate mi gracia; porque mi poder se perfecciona en la debilidad. Por tanto, de buena gana me gloriaré más bien en mis debilidades, para que repose sobre mí el poder de Cristo.' },
    { book: 'Zacarías', chapter: '4', verse: '6', text: 'Entonces respondió y me habló diciendo: Esta es palabra de Jehová a Zorobabel, que dice: No con ejército, ni con fuerza, sino con mi Espíritu, ha dicho Jehová de los ejércitos.' },
    { book: 'Gálatas', chapter: '6', verse: '9', text: 'No nos cansemos, pues, de hacer bien; porque a su tiempo segaremos, si no desmayamos.' },
    { book: 'Colosenses', chapter: '3', verse: '23', text: 'Y todo lo que hagáis, hacedlo de corazón, como para el Señor y no para los hombres.' },

    // --- EL AMOR ---
    { book: '1 Corintios', chapter: '13', verse: '4-5', text: 'El amor es sufrido, es benigno; el amor no tiene envidia, el amor no es jactancioso, no se envanece; no hace nada indebido, no busca lo suyo, no se irrita, no guarda rencor.' },
    { book: '1 Corintios', chapter: '13', verse: '13', text: 'Y ahora permanecen la fe, la esperanza y el amor, estos tres; pero el mayor de ellos es el amor.' },
    { book: '1 Juan', chapter: '4', verse: '8', text: 'El que no ama, no ha conocido a Dios; porque Dios es amor.' },
    { book: '1 Juan', chapter: '4', verse: '18', text: 'En el amor no hay temor, sino que el perfecto amor echa fuera el temor; porque el temor lleva en sí castigo. De donde el que teme, no ha sido perfeccionado en el amor.' },
    { book: '1 Juan', chapter: '4', verse: '19', text: 'Nosotros le amamos a él, porque él nos amó primero.' },
    { book: 'Juan', chapter: '3', verse: '16', text: 'Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna.' },
    { book: 'Juan', chapter: '15', verse: '13', text: 'Nadie tiene mayor amor que este, que uno ponga su vida por sus amigos.' },
    { book: 'Romanos', chapter: '5', verse: '8', text: 'Mas Dios muestra su amor para con nosotros, en que siendo aún pecadores, Cristo murió por nosotros.' },
    { book: 'Colosenses', chapter: '3', verse: '14', text: 'Y sobre todas estas cosas vestíos de amor, que es el vínculo perfecto.' },
    { book: 'Efesios', chapter: '5', verse: '2', text: 'Y andad en amor, como también Cristo nos amó, y se entregó a sí mismo por nosotros, ofrenda y sacrificio a Dios en olor fragante.' },
    { book: 'Proverbios', chapter: '10', verse: '12', text: 'El odio despierta rencillas; Pero el amor cubrirá todas las faltas.' },
    { book: '1 Pedro', chapter: '4', verse: '8', text: 'Y ante todo, tened entre vosotros ferviente amor; porque el amor cubrirá multitud de pecados.' },
    { book: '1 Corintios', chapter: '16', verse: '14', text: 'Todas vuestras cosas sean hechas con amor.' },
    { book: 'Gálatas', chapter: '5', verse: '22-23', text: 'Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre, templanza; contra tales cosas no hay ley.' },
    { book: 'Cantares', chapter: '8', verse: '7', text: 'Las muchas aguas no podrán apagar el amor, Ni lo ahogarán los ríos. Si diese el hombre todos los bienes de su casa por este amor, De cierto lo menospreciarían.' },
    { book: 'Romanos', chapter: '8', verse: '38-39', text: 'Por lo cual estoy seguro de que ni la muerte, ni la vida, ni ángeles, ni principados, ni potestades, ni lo presente, ni lo por venir... nos podrá separar del amor de Dios.' },
    { book: 'Proverbios', chapter: '17', verse: '17', text: 'En todo tiempo ama el amigo, Y es como un hermano en tiempo de angustia.' },
    { book: 'Mateo', chapter: '22', verse: '37-39', text: 'Amarás al Señor tu Dios con todo tu corazón, y con toda tu alma, y con toda tu mente. Este es el primero y grande mandamiento. Y el segundo es semejante: Amarás a tu prójimo como a ti mismo.' },

    // --- LA JUVENTUD ---
    { book: 'Eclesiastés', chapter: '11', verse: '9', text: 'Alégrate, joven, en tu juventud, y tome placer tu corazón en los días de tu adolescencia; y anda en los caminos de tu corazón y en la vista de tus ojos; pero sabe, que sobre todas estas cosas te juzgará Dios.' },
    { book: 'Eclesiastés', chapter: '12', verse: '1', text: 'Acuérdate de tu Creador en los días de tu juventud, antes que vengan los días malos, y lleguen los años de los cuales digas: No tengo en ellos contentamiento.' },
    { book: '1 Timoteo', chapter: '4', verse: '12', text: 'Ninguno tenga en poco tu juventud, sino sé ejemplo de los creyentes en palabra, conducta, amor, espíritu, fe y pureza.' },
    { book: 'Salmos', chapter: '119', verse: '9', text: '¿Con qué limpiará el joven su camino? Con guardar tu palabra.' },
    { book: 'Proverbios', chapter: '20', verse: '29', text: 'La gloria de los jóvenes es su fuerza, Y la hermosura de los ancianos es su vejez.' },
    { book: 'Lamentaciones', chapter: '3', verse: '27', text: 'Bueno le es al hombre llevar el yugo desde su juventud.' },
    { book: '2 Timoteo', chapter: '2', verse: '22', text: 'Huye también de las pasiones juveniles, y sigue la justicia, la fe, el amor y la paz, con los que de corazón limpio invocan al Señor.' },
    { book: 'Tito', chapter: '2', verse: '6-7', text: 'Exhorta asimismo a los jóvenes a que sean prudentes; presentándote tú en todo como ejemplo de buenas obras; en la enseñanza mostrando integridad, seriedad.' },
    { book: '1 Juan', chapter: '2', verse: '14', text: 'Os he escrito a vosotros, jóvenes, porque sois fuertes, y la palabra de Dios permanece en vosotros, y habéis vencido al maligno.' },
    { book: 'Jeremías', chapter: '1', verse: '7', text: 'Y me dijo Jehová: No digas: Soy un niño; porque a todo lo que te envíe irás tú, y dirás todo lo que te mande.' },
    { book: 'Proverbios', chapter: '1', verse: '8', text: 'Oye, hijo mío, la instrucción de tu padre, Y no desprecies la dirección de tu madre.' },
    { book: 'Proverbios', chapter: '23', verse: '22', text: 'Oye a tu padre, a aquel que te engendró; Y cuando tu madre envejeciere, no la menosprecies.' },
    { book: 'Deuteronomio', chapter: '6', verse: '6-7', text: 'Y estas palabras que yo te mando hoy, estarán sobre tu corazón; y las repetirás a tus hijos, y hablarás de ellas estando en tu casa, y andando por el camino, y al acostarte, y cuando te levantes.' },

    // --- EL PECADO, INMORALIDAD Y VICIOS ---
    { book: 'Romanos', chapter: '3', verse: '23', text: 'Por cuanto todos pecaron, y están destituidos de la gloria de Dios.' },
    { book: 'Romanos', chapter: '6', verse: '23', text: 'Porque la paga del pecado es muerte, mas la dádiva de Dios es vida eterna en Cristo Jesús Señor nuestro.' },
    { book: '1 Juan', chapter: '1', verse: '9', text: 'Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados, y limpiarnos de toda maldad.' },
    { book: 'Proverbios', chapter: '28', verse: '13', text: 'El que encubre sus pecados no prosperará; Mas el que los confiesa y se aparta alcanzará misericordia.' },
    { book: 'Salmos', chapter: '51', verse: '10', text: 'Crea en mí, oh Dios, un corazón limpio, Y renueva un espíritu recto dentro de mí.' },
    { book: 'Santiago', chapter: '1', verse: '15', text: 'Entonces la concupiscencia, después que ha concebido, da a luz el pecado; y el pecado, siendo consumado, da a luz la muerte.' },
    { book: '1 Corintios', chapter: '6', verse: '18', text: 'Huid de la fornicación. Cualquier otro pecado que el hombre cometa, está fuera del cuerpo; mas el que fornica, contra su propio cuerpo peca.' },
    { book: '1 Tesalonicenses', chapter: '4', verse: '3', text: 'Pues la voluntad de Dios es vuestra santificación; que os apartéis de fornicación.' },
    { book: 'Hebreos', chapter: '13', verse: '4', text: 'Honroso sea en todos el matrimonio, y el lecho sin mancilla; pero a los fornicarios y a los adúlteros los juzgará Dios.' },
    { book: 'Efesios', chapter: '5', verse: '3', text: 'Pero fornicación y toda inmundicia, o avaricia, ni aun se nombre entre vosotros, como conviene a santos.' },
    { book: 'Colosenses', chapter: '3', verse: '5', text: 'Haced morir, pues, lo terrenal en vosotros: fornicación, impureza, pasiones desordenadas, malos deseos y avaricia, que es idolatría.' },
    { book: 'Gálatas', chapter: '5', verse: '19-21', text: 'Y manifiestas son las obras de la carne, que son: adulterio, fornicación, inmundicia, lascivia, idolatría, hechicerías, enemistades, pleitos, celos, iras, contiendas, disensiones, herejías, envidias, homicidios, borracheras, orgías, y cosas semejantes a estas...' },
    { book: '1 Pedro', chapter: '2', verse: '11', text: 'Amados, yo os ruego como a extranjeros y peregrinos, que os abstengáis de los deseos carnales que batallan contra el alma.' },
    { book: 'Romanos', chapter: '12', verse: '2', text: 'No os conforméis a este siglo, sino transformaos por medio de la renovación de vuestro entendimiento, para que comprobéis cuál sea la buena voluntad de Dios, agradable y perfecta.' },
    { book: 'Isaías', chapter: '1', verse: '18', text: 'Venid luego, dice Jehová, y estemos a cuenta: si vuestros pecados fueren como la grana, como la nieve serán emblanquecidos; si fueren rojos como el carmesí, vendrán a ser como blanca lana.' },
    { book: 'Proverbios', chapter: '6', verse: '27', text: '¿Tomará el hombre fuego en su seno Sin que sus vestidos ardan?' },
    { book: '1 Corintios', chapter: '10', verse: '13', text: 'No os ha sobrevenido ninguna tentación que no sea humana; pero fiel es Dios, que no os dejará ser tentados más de lo que podéis resistir, sino que dará también juntamente con la tentación la salida, para que podáis soportar.' },
    { book: 'Mateo', chapter: '5', verse: '28', text: 'Pero yo os digo que cualquiera que mira a una mujer para codiciarla, ya adulteró con ella en su corazón.' },
    { book: 'Salmos', chapter: '103', verse: '12', text: 'Cuanto está lejos el oriente del occidente, Hizo alejar de nosotros nuestras rebeliones.' },
    { book: 'Efesios', chapter: '4', verse: '22-24', text: 'En cuanto a la pasada manera de vivir, despojaos del viejo hombre, que está viciado conforme a los deseos engañosos, y renovaos en el espíritu de vuestra mente, y vestíos del nuevo hombre, creado según Dios en la justicia y santidad de la verdad.' },
    { book: 'Santiago', chapter: '4', verse: '7', text: 'Someteos, pues, a Dios; resistid al diablo, y huirá de vosotros.' },
    { book: '1 Juan', chapter: '1', verse: '7', text: 'Pero si andamos en luz, como él está en luz, tenemos comunión unos con otros, y la sangre de Jesucristo su Hijo nos limpia de todo pecado.' },
    { book: 'Miqueas', chapter: '7', verse: '19', text: 'Él volverá a tener misericordia de nosotros; sepultará nuestras iniquidades, y echará en lo profundo del mar todos nuestros pecados.' },
    { book: '2 Corintios', chapter: '5', verse: '17', text: 'De modo que si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron; he aquí todas son hechas nuevas.' },

    // --- ESPERANZA, PAZ Y SALVACIÓN ---
    { book: 'Juan', chapter: '16', verse: '33', text: 'Estas cosas os he hablado para que en mí tengáis paz. En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo.' },
    { book: 'Romanos', chapter: '15', verse: '13', text: 'Y el Dios de esperanza os llene de todo gozo y paz en el creer, para que abundéis en esperanza por el poder del Espíritu Santo.' },
    { book: 'Filipenses', chapter: '4', verse: '6-7', text: 'Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con acción de gracias. Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús.' },
    { book: '1 Pedro', chapter: '5', verse: '7', text: 'Echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros.' },
    { book: 'Hebreos', chapter: '4', verse: '16', text: 'Acerquémonos, pues, confiadamente al trono de la gracia, para alcanzar misericordia y hallar gracia para el oportuno socorro.' },
    { book: 'Salmos', chapter: '121', verse: '1-2', text: 'Alzaré mis ojos a los montes; ¿De dónde vendrá mi socorro? Mi socorro viene de Jehová, Que hizo los cielos y la tierra.' },
    { book: 'Isaías', chapter: '26', verse: '3', text: 'Tú guardarás en completa paz a aquel cuyo pensamiento en ti persevera; porque en ti ha confiado.' },
    { book: 'Mateo', chapter: '6', verse: '33', text: 'Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.' },
    { book: 'Efesios', chapter: '2', verse: '8', text: 'Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios.' },
    { book: 'Romanos', chapter: '10', verse: '9', text: 'Que si confesares con tu boca que Jesús es el Señor, y creyeres en tu corazón que Dios le levantó de los muertos, serás salvo.' },
    { book: 'Juan', chapter: '10', verse: '28', text: 'Y yo les doy vida eterna; y no perecerán jamás, ni nadie las arrebatará de mi mano.' },
    { book: 'Salmos', chapter: '37', verse: '4', text: 'Deléitate asimismo en Jehová, Y él te concederá las peticiones de tu corazón.' },
    { book: 'Salmos', chapter: '91', verse: '1', text: 'El que habita al abrigo del Altísimo Morará bajo la sombra del Omnipotente.' },
    { book: 'Lamentaciones', chapter: '3', verse: '22-23', text: 'Por la misericordia de Jehová no hemos sido consumidos, porque nunca decayeron sus misericordias. Nuevas son cada mañana; grande es tu fidelidad.' },
    { book: 'Romanos', chapter: '12', verse: '12', text: 'Gozosos en la esperanza; sufridos en la tribulación; constantes en la oración.' },
    { book: 'Zofonías', chapter: '3', verse: '17', text: 'Jehová en medio de ti, poderoso, él salvará; se gozará sobre ti con alegría, callará de amor, se regocijará sobre ti con cánticos.' },
    { book: '2 Timoteo', chapter: '3', verse: '16', text: 'Toda la Escritura es inspirada por Dios, y útil para enseñar, para redargüir, para corregir, para instruir en justicia.' },
    { book: 'Mateo', chapter: '28', verse: '20', text: 'Enseñándoles que guarden todas las cosas que os he mandado; y he aquí yo estoy con vosotros todos los días, hasta el fin del mundo. Amén.' },
    { book: 'Santiago', chapter: '1', verse: '5', text: 'Y si alguno de vosotros tiene falta de sabiduría, pídala a Dios, el cual da a todos abundantemente y sin reproche, y le será dada.' },
    { book: '1 Juan', chapter: '5', verse: '14', text: 'Y esta es la confianza que tenemos en él, que si pedimos alguna cosa conforme a su voluntad, él nos oye.' },

    // --- OTRAS TEMÁTICAS VITALES (Trabajo, Lengua, Amistad) ---
    { book: 'Proverbios', chapter: '16', verse: '3', text: 'Encomienda a Jehová tus obras, Y tus pensamientos serán afirmados.' },
    { book: 'Mateo', chapter: '12', verse: '36', text: 'Mas yo os digo que de toda palabra ociosa que hablen los hombres, de ella darán cuenta en el día del juicio.' },
    { book: 'Proverbios', chapter: '15', verse: '1', text: 'La blanda respuesta quita la ira; Mas la palabra áspera hace subir el furor.' },
    { book: 'Colosenses', chapter: '4', verse: '6', text: 'Sea vuestra palabra siempre con gracia, sazonada con sal, para que sepáis cómo habéis de responder a cada uno.' },
    { book: 'Proverbios', chapter: '13', verse: '20', text: 'El que anda con sabios, sabio será; Mas el que se junta con necios será quebrantado.' },
    { book: 'Proverbios', chapter: '27', verse: '17', text: 'Hierro con hierro se aguza; Y así el hombre aguza el rostro de su amigo.' },
    { book: 'Eclesiastés', chapter: '4', verse: '9', text: 'Mejores son dos que uno; porque tienen mejor paga de su trabajo.' },
    { book: 'Santiago', chapter: '3', verse: '9-10', text: 'Con ella bendecimos al Dios y Padre, y con ella maldecimos a los hombres, que están hechos a la semejanza de Dios. De una misma boca proceden bendición y maldición. Hermanos míos, esto no debe ser así.' },
    { book: 'Proverbios', chapter: '4', verse: '23', text: 'Sobre toda cosa guardada, guarda tu corazón; Porque de él mana la vida.' },
    { book: 'Efesios', chapter: '4', verse: '29', text: 'Ninguna palabra corrompida salga de vuestra boca, sino la que sea buena para la necesaria edificación, a fin de dar gracia a los oyentes.' },
    { book: 'Hebreos', chapter: '13', verse: '5', text: 'Sean vuestras costumbres sin avaricia, contentos con lo que tenéis ahora; porque él dijo: No te desampararé, ni te dejaré.' },
    { book: '1 Pedro', chapter: '3', verse: '10', text: 'Porque: El que quiere amar la vida Y ver días buenos, Refrene su lengua de mal, Y sus labios no hablen engaño.' },
    { book: 'Efesios', chapter: '5', verse: '15-16', text: 'Mirad, pues, con diligencia cómo andéis, no como necios sino como sabios, aprovechando bien el tiempo, porque los días son malos.' },
    { book: 'Proverbios', chapter: '14', verse: '12', text: 'Hay camino que al hombre le parece derecho; Pero su fin es camino de muerte.' },
    { book: '2 Pedro', chapter: '3', verse: '9', text: 'El Señor no retarda su promesa, según algunos la tienen por tardanza, sino que es paciente para con nosotros, no queriendo que ninguno perezca, sino que todos procedan al arrepentimiento.' },
    { book: 'Juan', chapter: '8', verse: '32', text: 'Y conoceréis la verdad, y la verdad os hará libres.' },
    { book: 'Gálatas', chapter: '2', verse: '20', text: 'Con Cristo estoy juntamente crucificado, y ya no vivo yo, mas vive Cristo en mí; y lo que ahora vivo en la carne, lo vivo en la fe del Hijo de Dios, el cual me amó y se entregó a sí mismo por mí.' },
    { book: 'Efesios', chapter: '6', verse: '11', text: 'Vestíos de toda la armadura de Dios, para que podáis estar firmes contra las asechanzas del diablo.' },
    { book: 'Santiago', chapter: '1', verse: '22', text: 'Pero sed hacedores de la palabra, y no tan solamente oidores, engañándoos a vosotros mismos.' },
    { book: '1 Juan', chapter: '2', verse: '15', text: 'No améis al mundo, ni las cosas que están en el mundo. Si alguno ama al mundo, el amor del Padre no está en él.' }
];

export const getRandomFallbackVerse = () => {
    // Al usar minTimestamp % length, aseguramos un bloque persistente
    // cada 2 horas globalmente sin repetirse inmediatamente a menos que length sea pequeño
    // NOTA: Como agregamos >100 versículos, el índice saltará naturalmente garantizando
    // variedad durante varias semanas sin repetir versículos frecuentemente.
    const minTimestamp = Math.floor(Date.now() / (1000 * 60 * 60 * 2));
    const index = minTimestamp % FALLBACK_VERSES.length;
    return FALLBACK_VERSES[index];
};
